name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/test

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3 # adapte selon ta version
          bundler-cache: true

      - name: Install system dependencies
        run: sudo apt-get install -y libvips postgresql-client

      - name: Set up database
        run: |
          cp config/database.yml.github config/database.yml
          bin/rails db:create
          bin/rails db:schema:load

      - name: Rubocop
        run: bundle exec rubocop --parallel

      - name: Brakeman
        run: bundle exec brakeman -q -w2

      - name: Run RSpec
        run: bundle exec rspec
