name: Ruby on Rails CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/o_n_my_god_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips postgresql-client
          gem install bundler
          bundle install

      - name: Prepare database
        run: |
          cp config/database.yml config/database.yml.bak
          echo "test:\n  adapter: postgresql\n  encoding: unicode\n  database: o_n_my_god_test\n  username: postgres\n  password: password\n  host: localhost" > config/database.yml
          bin/rails db:prepare

      - name: Run Rubocop
        run: bundle exec rubocop --parallel

      - name: Run Brakeman
        run: bundle exec brakeman -q -w2

      - name: Run RSpec tests
        run: bundle exec rspec
